<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from rrbot.xacro                    | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
 <!-- Import Rviz colors -->  
<material name="black">
 <color rgba="0.0 0.0 0.0 1.0"/>  
 </material>

<material name="blue">    
  <color rgba="0.0 0.0 0.8 1.0"/>  
  </material>

 <material name="green">    
  <color rgba="0.0 1.0 0.0 1.0"/>  
  </material>

<material name="grey">    
  <color rgba="0.2 0.2 0.2 1.0"/>  
  </material>

   <material name="orange">    
  <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>  
  </material>

 <material name="brown">    
  <color rgba="${222/255} ${207/255} ${195/255} 1.0"/>  
  </material>

 <material name="red">    
  <color rgba="0.8 0.0 0.0 1.0"/>  
  </material>

 <material name="white">    
  <color rgba="1.0 1.0 1.0 1.0"/>  
  </material>
 
  <!-- Default Inertial -->  
  <xacro:macro name="default_inertial" params="z_value i_value mass">    
  <inertial>      
  <origin xyz="0 0 ${z_value}" rpy="0 0 0"/>      
  <mass value="${mass}" />      
  <inertia ixx="${i_value}" ixy="0.0" ixz="0.0"               iyy="${i_value}" iyz="0.0"  izz="${i_value}" />     
   </inertial>  
   </xacro:macro>
 
 <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>
  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>
  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 1.0"/>
      <geometry>
        <box size="0.1 0.1 2"/>
      </geometry>
    </collision>
    <xacro:default_inertial z_value="${height1/2}"               
                 i_value="1.0" mass="1"/> 
    <visual>
     <material name="red"/>
      <origin rpy="0 0 0" xyz="0 0 1.0"/>
      <geometry>
        <box size="0.1 0.1 2"/>
      </geometry>
     
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 1.0"/>
      <mass value="1"/>
      <inertia ixx="0.334166666667" ixy="0.0" ixz="0.0" iyy="0.334166666667" iyz="0.0" izz="0.00166666666667"/>
    </inertial>
  </link>
  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin rpy="0 0 0" xyz="0 0.1 1.95"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>
  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.45"/>
      <geometry>
        <box size="0.1 0.1 1"/>
      </geometry>
    </collision>
     <xacro:default_inertial z_value="${height2/2 - axle_offset}"    i_value="1.0" mass="1"/> 
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.45"/>
      <geometry>
        <box size="0.1 0.1 1"/>
      </geometry>
      <material name="green"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.45"/>
      <mass value="1"/>
      <inertia ixx="0.0841666666667" ixy="0.0" ixz="0.0" iyy="0.0841666666667" iyz="0.0" izz="0.00166666666667"/>
    </inertial>
  </link>
  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin rpy="0 0 0" xyz="0 0.1 0.9"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>
  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.45"/>
      <geometry>
        <box size="0.1 0.1 1"/>
      </geometry>
    </collision>
        <xacro:default_inertial z_value="${height3/2 - axle_offset}"      i_value="1.0" mass="1"/>  
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.45"/>
      <geometry>
        <box size="0.1 0.1 1"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.45"/>
      <mass value="1"/>
      <inertia ixx="0.0841666666667" ixy="0.0" ixz="0.0" iyy="0.0841666666667" iyz="0.0" izz="0.00166666666667"/>
    </inertial>
  </link>
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
 
 <!-- Gripper Link -->>
    <link name="left_gripper">    
      <visual>      
      <origin rpy="0 0 0" xyz="0 0 0"/>      
      <geometry>       
      <mesh filename="package://pr2_description/meshes/l_finger.dae"/>     
          </geometry>    
          </visual> 


 <!-- Gripper -->  
  <joint name="left_gripper_joint" type="revolute">    
  <parent link="link3"/>    
  <child link="left_gripper"/>   
   <origin xyz="0 0 ${height2 - axle_offset}" rpy="0 -1.57 0"/>    
   <axis xyz="0 0 1"/>    <limit effort="30.0" lower="-0.548" upper="0.0"  velocity="0.1"/>  
   </joint>
  <link name="left_gripper">    
  <visual>      
  <origin rpy="0 0 0" xyz="0 0 0"/>      
  <geometry>        
  <mesh filename="$(find test_robot)/meshes/l_finger.dae"/>      
  </geometry>    
  </visual>
    <collision>      
    <geometry>        
    <box size="0.1 0.1 0.1"/>      
    </geometry>    
    </collision>    
    <xacro:default_inertial z_value="0" i_value="0.000001"  mass="1"/>  
    </link>   <joint name="left_tip_joint" type="fixed">    
    <parent link="left_gripper"/>    
    <child link="left_tip"/>  
    </joint>
  <link name="left_tip">    
  <visual>      
  <origin rpy="0 0 0" xyz="0.09137 0.00495 0"/>      
  <geometry>        
  <mesh          filename="$(find test_robot)/meshes/l_finger_tip.dae"/>      
  </geometry>   
   </visual>
    <collision>      
    <geometry>        
    <box size="0.1 0.1 0.1"/>      
    </geometry>    
    </collision>    
    <xacro:default_inertial z_value="0" i_value="1e-6" mass="1e- 5"/>  
    </link>
  <joint name="right_gripper_joint" type="revolute">    
  <parent link="top_link"/>    
  <child link="right_gripper"/>    
  <origin xyz="0 0 ${height2 - axle_offset}" rpy="0 -1.57 0"/>    
  <axis xyz="0 0 -1"/>   
   <limit effort="30.0" lower="0.0" upper="0.548"  velocity="0.5"/> 
    </joint>
  <link name="right_gripper">    
  <visual>      
  <origin rpy="3.1415 0 0" xyz="0 0 0"/>     
   <geometry>        
   <mesh filename="$(find test_robot)/meshes/l_finger.dae"/>      
   </geometry>    
   </visual> 
   <collision>      
   <geometry>        
   <box size="0.1 .1 .1"/>     
    </geometry>    
    </collision>    
    <xacro:default_inertial z_value="0" i_value="1e-6" mass="1"/>  
    </link>
  <joint name="right_tip_joint" type="fixed">    
  <parent link="right_gripper"/>   
   <child link="right_tip"/>  
   </joint>
  <link name="right_tip">    
  <visual>     
   <origin rpy="-3.1415 0 0" xyz="0.09137 0.00495 0"/>      
   <geometry>        
   <mesh           filename="$(find test_robot)/meshes/l_finger_tip.dae"/>      
   </geometry>    
   </visual>
    <collision>     
     <geometry>       
      <box size="0.1 .1 .1"/>     
       </geometry>    
       </collision>    
       <xacro:default_inertial z_value="0" i_value="1e-6" mass="1e- 5"/>  
       </link> 

</robot>